export const GET_STUDENTS = 'GET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const SELECTED_STUDENT = 'SELECTED_STUDENT';
